id: opecha:P004394
initial_creation_type: ocr
source_metadata:
  id: bdr:W9086
  title: ཡི་དམ་དགོངས་འདུས་རྟ་མཆོག་རོལ་པའི་གཏེར་འབྱུང་དགའ་བའི་རྣ་རྒྱན་དང་། སྟག་ཤམ་དྲུག་པའི་གསན་ཡིག་ནོར་བུའི་ཕྲེང་བ།
  volume: ''
  author: ''
