id: I3C416BD6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:39:09+00:00'
last_modified: '2022-06-07T22:33:25.858188+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9086
  title: ཡི་དམ་དགོངས་འདུས་རྟ་མཆོག་རོལ་པའི་གཏེར་འབྱུང་དགའ་བའི་རྣ་རྒྱན་དང་། སྟག་ཤམ་དྲུག་པའི་གསན་ཡིག་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1E37:
      image_group_id: I1PD106319
      title: ''
      total_pages: 320
      order: 1
      base_file: 1E37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
